using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using static System.Collections.Generic.Dictionary<string, object>;

namespace IVSoftware.Portable.Threading
{
    /// <summary>
    /// Represents event data that, by default, behaves like a dictionary but can be overridden by the user with any type of object.
    /// </summary>
    public class AwaitedEventArgs : EventArgs, IEnumerable
    {
        /// <summary>
        /// Constructs a new instance of AwaitedEventArgs, defaulting to use a dictionary for storing event data.
        /// </summary>
        /// <remarks>
        /// HEURISTIC: When call site supplies a single, unnamed arg:
        /// - It is ALWAYS attributed as a caller (even it the formatting indicates 
        ///   that it couldn't possibly be a legal CallerMemberName.
        /// - What we can't be certain of is whether the call site intends this as
        ///   the Args value of type string, i.e. will be looking for it in that slot.
        /// - We're going to tilt in favor of the posit that if value looks like a
        ///   legal [CallerMemberName] - and this includes generic indexers like e.g.
        ///   the test case of `System.Collections.Generic.IList<T>.Item` then log it
        ///   as the caller only and leave Args pointed to the dict (for early adopters).
        /// IN MODERN VERSIONS:
        /// - This is less critical because 'this' is still going to be a dict even
        ///   if Args has been replaced by something else (because by default it points
        ///   to the dict). We're still not going to break the Rev OR contract, however.
        /// - In other words, in early versions the Args had to be one one or the other.
        /// </remarks>
        public AwaitedEventArgs([CallerMemberName] string caller = null)
        : this(args: NullObject, caller: caller) { }

        private static object NullObject = new object();

        /// <summary>
        /// Constructs a new instance of AwaitedEventArgs, allowing for the Args property to be set with a custom object.
        /// </summary>
        [Canonical]
        public AwaitedEventArgs(object args, [CallerMemberName] string caller = null)
        {
            // This is non-negotiable, because the single argument (or parameterless)
            // call has forwarded what it has as the incoming caller arg.
            Caller = caller;

            if(args != null && caller != null && !Equals(args, NullObject))
            {
                // This if a fully qualified call from the start.
                _args = args;
            }
            else
            {
                if(localDisqualifyAsCompilerGenerated())
                {
                    _args = caller;
                }
                // This means we have only 'caller' to work with. The question is,
                // did the compiler populate it or was it used as a tag by EUD?

                #region L o c a l F x 
                bool localDisqualifyAsCompilerGenerated()
                {
                    var aspirant = caller;
                    if (string.IsNullOrWhiteSpace(aspirant))
                        return false; // Empty, whitespace-only, or null => treat as user-supplied tag.

                    var trimmed = aspirant.Trim();

                    // Rule 1: Disqualify for inner whitespace.
                    // (Compiler never emits whitespace inside CallerMemberName)
                    if (trimmed.Any(ch => char.IsWhiteSpace(ch)))
                        return true;

                    // Rule 2: Disqualify if starts with a digit.
                    if (char.IsDigit(trimmed[0]))
                        return true;

                    // Rule 3: Disqualify if dotted at either edge
                    if (trimmed.StartsWith(".") || trimmed.EndsWith("."))
                        return true; // Disqualified

                    // Rule 4: Disqualify if brackets unmatched
                    if (trimmed.Contains("<") ^ trimmed.Contains(">"))
                        return true;

                    // Anything else is likely to have been generated by the compiler.
                    return false;
                }
                #endregion L o c a l F x
            }
        }


        /// <summary>
        /// By default, this object behaves like a dictionary, storing key-value pairs.
        /// </summary>
        public object Args => _args ?? _dict;

        public object _args = null;

        private readonly Dictionary<string, object> _dict = new Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the AwaitedEventArgs class with the calling method's name as the caller.
        /// </summary>
        /// <param name="caller">The name of the method that instantiated the object, automatically captured.</param>
        public string Caller { get; }

        /// <summary>
        /// Adds a key-value pair to the Args dictionary, enabling the use of collection initializer syntax.
        /// Throws an exception if Args is not a dictionary.
        /// </summary>
        /// <param name="key">The key for the value to be stored.</param>
        /// <param name="value">The value to be stored.</param>
        /// <remarks>
        /// This method allows the AwaitedEventArgs to be initialized or modified using collection initializer syntax
        /// as long as Args is in its default dictionary form, enhancing ease of use when setting multiple key-value pairs.
        /// </remarks>
        public void Add(string key, object value)
        {
            if (Args is Dictionary<string, object> dict)
            {
                dict[key] = value; // Using indexer to allow overwriting existing keys.
            }
            else
            {
                _dict[key] = value; // Using indexer to allow overwriting existing keys.
            }
        }

        /// <summary>
        /// Adds a key-value pair to the Args dictionary using an enumeration as the key, enabling the use of collection initializer syntax.
        /// Throws an exception if Args is not a dictionary.
        /// </summary>
        /// <param name="stdKey">The enumeration key to be converted to a string and used as the key for the value to be stored.</param>
        /// <param name="value">The value to be stored.</param>
        /// <remarks>
        /// This method extends the functionality to use enumeration values as keys by converting them to their string representations. 
        /// It allows the AwaitedEventArgs to be initialized or modified using collection initializer syntax
        /// as long as Args is in its default dictionary form, enhancing ease of use when setting multiple key-value pairs.
        /// This is particularly useful when enum values represent a set of predefined keys.
        /// </remarks>
        public void Add(Enum stdKey, object value)
        {
            if (Args is Dictionary<string, object> dict)
            {
                dict[stdKey.ToString()] = value; // Using indexer to allow overwriting existing keys.
            }
            else
            {
                throw new InvalidOperationException("Cannot add key-value pairs when Args is not a dictionary.");
            }
        }


        public object this[string key, bool @throw = false]
        {
            get
            {
                // Inspect object with the modern allowance for 'hybrid' initialization 
                //where this.Args is not a dict but 'this' still is.
                Dictionary<string, object> dict =
                    Args is Dictionary<string, object> fromArgs
                    ? fromArgs
                    : _dict;
                if (dict.TryGetValue(key, out var value))
                {
                    return value;
                }
                else if (@throw)
                {
                    throw new KeyNotFoundException("The given key was not present in the dictionary.");
                }
                else return default;
            }
            set
            {
                Dictionary<string, object> dict =
                    Args is Dictionary<string, object> fromArgs
                    ? fromArgs
                    : _dict;
                    dict[key] = value;  // Adds or updates the key with the provided value.
            }
        }

        /// <summary>
        /// Retrieves or sets a value by converting an enumeration key to its string representation and using it to access the dictionary.
        /// This method simplifies the use of enumeration values as keys for dictionary operations.
        /// </summary>
        /// <param name="stdKey">The enumeration key to be converted to a string and used for dictionary access.</param>
        /// <param name="throw">If true, enables throwing of exceptions. A KeyNotFoundException is thrown if the key is not found,
        /// and an InvalidOperationException is thrown if the Args property is not a dictionary.</param>
        /// <returns>The value associated with the specified enumeration key.</returns>
        public object this[Enum stdKey, bool @throw = false]
        {
            get => this[stdKey.ToString()];
            set => this[stdKey.ToString()] = value;
        }

        /// <summary>
        /// Provides an enumerator for the Args property if it is an IEnumerable.
        /// </summary>
        /// <returns>An IEnumerator for the Args if it is enumerable, or an empty enumerator if it is not.</returns>
        public IEnumerator GetEnumerator()
        {
            if (Args is IEnumerable enumerable)
            {
                return enumerable.GetEnumerator();
            }
            return Enumerable.Empty<object>().GetEnumerator();
        }

        /// <summary>
        /// Tries to retrieve a value by key from the Args property when it is a dictionary, casting it to the specified type.
        /// This method provides a way to attempt to retrieve values without throwing exceptions,
        /// returning a boolean indicating success or failure.
        /// </summary>
        /// <param name="key">The key of the value to retrieve.</param>
        /// <param name="value">The value associated with the specified key, if found and successfully cast; otherwise, default value of type T.</param>
        /// <returns>True if the key is found, the value exists and is of type T; otherwise, false.</returns>
        /// <typeparam name="T">The type to which the retrieved value should be cast.</typeparam>
        public bool TryGetValue<T>(string key, out T value)
        {
            if (_dict.TryGetValue(key, out var unk) && unk is T valueT)
            {
                value = valueT;
                return true;
            }
            value = default;
            return false;
        }

        /// <summary>
        /// Tolerant retriaval of a typed value by T
        /// </summary>
        public T GetValue<T>(string key, bool @throw = false)
        {
            if (_dict.TryGetValue(key, out var unk) && unk is T valueT)
            {
                return valueT;
            }
            else
            {
                if(@throw)
                {
                    throw new KeyNotFoundException(key);
                }
                return default;
            }
        }


        public int Count => _dict.Count;
        /// <summary>
        /// Gets the collection of keys contained in the underlying dictionary.
        /// </summary>
        public KeyCollection Keys => _dict.Keys;

        /// <summary>
        /// Gets the collection of values contained in the underlying dictionary.
        /// </summary>
        public ValueCollection Values => _dict.Values;

        /// <summary>
        /// Determines whether the underlying dictionary contains a specific key.
        /// </summary>
        /// <param name="key">The key to locate in the dictionary.</param>
        /// <returns>true if the dictionary contains an element with the specified key; otherwise, false.</returns>
        public bool ContainsKey(string key) => _dict.ContainsKey(key);

        /// <summary>
        /// Determines whether the underlying dictionary contains a specific key, using an enumeration value as the key.
        /// </summary>
        /// <param name="stdKey">The enumeration key to convert to string and locate in the dictionary.</param>
        /// <returns>true if the dictionary contains an element with the specified key; otherwise, false.</returns>
        public bool ContainsKey(Enum stdKey) => _dict.ContainsKey(stdKey.ToString());

        internal static void RaiseSelf(object sender, AwaitedEventArgs e)
            => Awaited?.Invoke(sender, e);

        public static event EventHandler<AwaitedEventArgs> Awaited;
    }
}
