<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Multi-targeting: WinForms and MAUI -->
		<TargetFrameworks>net8.0-windows</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Enable WinForms -->
		<UseWindowsForms>true</UseWindowsForms>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>

		<!-- Enable MAUI -->
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>

		<!-- Enable WPF -->
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="IVSoftware.Portable.Disposable" Version="2.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageReference Include="MSTest" Version="3.6.4" />	  
		<!-- Allow prerelease for now (this is for MS Test only anyway)-->
		<PackageReference Include="IVSoftware.WinOS.MSTest.Extensions.STA" Version="1.0.0-*" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IVSoftware.Portable.Threading\IVSoftware.Portable.Threading.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
